language: go

go:
- 1.14.x

go_import_path: github.com/hyperledger-labs/fabric-smart-client

jobs:
  include:
    - stage:  Preliminaries
      script: make checks
    - stage:  Unit tests
      script: make unit-tests
    - stage:  Integration tests
      script: sudo systemctl restart docker && make integration-tests